### ISSUE TITLE
Broken lighting

### ISSUE THREAD

**Issue by ludwici** [Antop90fr1/CreateFactory#1]
For some reason, you can't see the fog when you're underwater. 
Screenshot 1 shows the problem
In screenshot 2 the mod is disabled
https://imgur.com/a/U81xr2c
Mod version: 0.4a-1.20.1
Forge version: 47.3.1

**Comment by Antop90fr1** [comment]
weird... I will try to fix this

**Comment by Antop90fr1** [comment]
_fixed in 0.4b version_
