### ISSUE TITLE
Breaks fishing and fish spawns

### ISSUE THREAD

**Issue by RexiaXIV** [Antop90fr1/CreateFactory#2]
When I downloaded the mod, fishing rod bobbers would sink immediately to the floor, whether vanilla or aquaculture rod. Also, fish, squid (glow and normal) and dolphins wouldn't spawn. Removing the mod fixed it. I only found out because post on reddit narrowed it down, though they were not playing the same modpack. 
(https://www.reddit.com/r/feedthebeast/comments/1dh776c/fishing_rod_not_working_properly_on_modded_client/)

Version 1.20.1, when added to Industrial Village modpack (as well as other food and QoL mods).

**Comment by Antop90fr1** [comment]
That's reaaally weird, I'm gonna try to fix this soon when I have time

**Comment by Antop90fr1** [comment]
_fixed in 0.4b version_
