### ISSUE TITLE
Mod causes water to become completely transparent when under water [1.20.1].

### ISSUE THREAD

**Issue by Gammamad** [Antop90fr1/CreateFactory#4]
When swimming there is no murkiness in water, you can se as far as draw distance. Removing mod fixes this issue.
Issue is present with and without renderer mods, optimization mods or shaders.

Minecraft version 1.20.1
OS Linux

**Comment by Antop90fr1** [comment]
It was fixed in the update of yesterday (0.4b). If this bug still occurs, let me know

**Comment by Gammamad** [comment]
It's still 0.4a on modrinth. I'll check CurseForge.

**Comment by Antop90fr1** [comment]
I forgot to update on modrinth.... I'm updating it now
